### ISSUE TITLE
I cannot see any entities

### ISSUE THREAD

**Issue by mricine** [Wind-Development/WindSpigot#117]
**Describe the bug**
I tried using the latest version of WindSpigot and I can't see any entities (from players to npcs).

**Bug on latest**
Is the bug on the latest version of WindSpigot? yes, it is

**To Reproduce**
- start a server with WindSpigot.

**Comment by windcolor-dev** [comment]
Should be fixed, but in the future please use the latest release of WindSpigot, not the dev builds
