### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by SkirmisLTU** [Wind-Development/WindSpigot#129]
**Describe the bug**
My server crashes after few minutes of playing. I am using latest WindSpigot and 1.19.4 client with [ViaVersion](https://github.com/ViaVersion/ViaVersion)

**Bug on latest**
Is the bug on the latest version of WindSpigot?
Yes

**To Reproduce**
1. Come on the server.
2. Mess around a bit, fight, build (for about 1-2 minutes at max)
3. Watch the server freeze and crash

**Expected behavior**
No crash

**Screenshots**
No applicable.

**Additional context**
logs: https://mclo.gs/kek9SJF

**Comment by GeorgeV220** [comment]
Hello, please remove the plugin com.andrei1058.bedwars (BedWars1058) and try again. Most probably an outdated plugin causes the issue.

**Comment by SkirmisLTU** [comment]
The plugin is not outdated, it’s extremely popular, and I already tried changing versions of it. I also contacted ViaVersion support, because I saw some errors from it. They said that it’s the fork. I switched to other fork now and it works fine, so it’s your fork, just letting you know.
