### ISSUE TITLE
Error when user quit - v2.1.0

### ISSUE THREAD

**Issue by hwalker928** [Wind-Development/WindSpigot#20]
**Describe the bug**

When a player is kicked from the server, or the server restarts and the player is connected, an error is thrown and then the player cannot connect properly afterwards until a server restart is performed.

EDIT: Additionally, it seems when the server is restarted, all OP'd players become regular players, and have to be `op <username>`'d again.

**Bug on latest**

BETA v2.1.0, Java 17
The issue is not present on v2.0.1

**To Reproduce**

- Player joins
- Kick the player from the console, using `kick <username>`, or simply restart the server whilst connected
- Error is thrown, as seen [here](https://bin.harryw.link/yuxohirise.md)
- Player is then unable to join, being stuck on "Downloading Terrain"
- Server is still responsive via the console

**Expected behaviour**

The player is kicked without any errors, and can then join successfully afterwards.

**Screenshots**

![image](https://user-images.githubusercontent.com/63236817/163693696-35c2409a-6ae8-4fa5-a1c4-c67f0f896093.png)

**Comment by windcolor-dev** [comment]
The join/kick bug is fixed. It turns out that the "faster-operators" config option from NachoSpigot is supposed to deop players after a restart. This is probably for quick testing or something like that.
