### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by HowardZHY** [Wind-Development/WindSpigot#29]
I know there are many plugin issues and abnormal behaves on Nacho , like 1.9+ players can't join when install Viaversion y Protocol Support at the same time.
So how many Nacho bugs was fixed by wind? Is it **stable** enough ? (just like Burrito)

**Comment by windcolor-dev** [comment]
WindSpigot doesn't fix any NachoSpigot bugs. I recommend using ViaVersion with ViaRewind + ViaBackwards instead of two different protocol hacks. However, if you find any issues with plugins, you can report them here.
