### ISSUE TITLE
TPS lock at max 19.7 using Java 17

### ISSUE THREAD

**Issue by Fredh1000** [Wind-Development/WindSpigot#33]
**Describe the bug**
When I start my server using java 17 and try to do / tps (using Spark as plugin), I see that everything is perfect and the tps crashes at MAXIMUM 19.7, this problem is not present when using Java 11 or Java 8 nor when using Paper 1.8.8 with Java 17.

**Bug on latest**
Yes, the bug is present in all versions of WindSpigot (even the dev builds) and also in those of NachoSpigot. I noticed that I am on Paper 1.8.8 the TPS would seem not to crash at 19.7 on Java 17. Also on SportPaper there is this bug, from what I remember also flamepaper should have the same problem.

**To Reproduce**
Use Java 17 with WindSpigot in localhost and start the server.

**Screenshots**
![2022-05-17_10 55 03](https://user-images.githubusercontent.com/82319919/168772132-2d6fcb5e-76c1-4c76-94cc-7ebc1a67b1f9.png)

**Additional context**
Java version used: Java 17.
WindSpigot version used: WindSpigot build Respect config option for async path searching WindSpigot Build and Upload #200.
Operative System Used: Windows 10.
RAM used to test: 4Gb.
Use of Aikar Flags: yes

**Comment by windcolor-dev** [comment]
Works fine for me, but I'm running Linux.

**Comment by Fredh1000** [comment]
Do you think this is a Windows problem? Many have told me this but I never understood why with Paper 1.8.8 there is no such problem on Windows.

**Comment by windcolor-dev** [comment]
No idea

**Comment by Fejm** [comment]
CPU?

**Comment by Fredh1000** [comment]
But the cpu has nothing to do with it, with Java 11 I make 20 TPS, with Java 17 I make a maximum of 19.7 on Windows. However Ryzen 7 2700x. However don't answer me "Then use Java 11", Java 17 does not cause me TPS loss, it is more stable and has the g1 old has 0, the only problem is this TPS lock at 19.7 maximum.

**Comment by Fejm** [comment]
> But the cpu has nothing to do with it, with Java 11 I make 20 TPS, with Java 17 I make a maximum of 19.7 on Windows. However Ryzen 7 2700x. However don't answer me "Then use Java 11", Java 17 does not cause me TPS loss, it is more stable and has the g1 old has 0, the only problem is this TPS lock at 19.7 maximum.

No, no, no! I have the same problem, I believe there is something wrong with the AMD processors. People with Intel don't have any problems.

**Comment by Fredh1000** [comment]
I don't think it is the fault of the cpu, if I use Paper 1.8.8 this problem does not happen to me even with Java 17. Then you had written on Nacho's GitHub that this problem also happened to you with Java 11, with Java 11 it is fine to me.

**Comment by Fejm** [comment]
> I don't think it is the fault of the cpu, if I use Paper 1.8.8 this problem does not happen to me even with Java 17. Then you had written on Nacho's GitHub that this problem also happened to you with Java 11, with Java 11 it is fine to me.

On old CPU (i7-4970k) i have 20 tps. On Ryzen i have 19.7. Tested on my old custom fork from past.

CPU is issue here.

**Comment by Fejm** [comment]
Found issue.

Removing those lines: https://github.com/Wind-Development/WindSpigot/blob/master/WindSpigot-Server/src/main/java/net/minecraft/server/MinecraftServer.java#L667-L677

Brings 20.00 tps back

15:24:19 [INFO]: WindSpigot Performance:
15:24:19 [INFO]: TPS from last 1m, 5m, 15m: 20.0, 20.0, 20.0

Tested: AMD CPU, JAVA 17, 4GB, no startup flags

**Comment by Fredh1000** [comment]
report it to Windcolor as soon as possible.

**Comment by Fejm** [comment]
@windcolor-dev

**Comment by Fredh1000** [comment]
Make a pull request directly if you can.

**Comment by windcolor-dev** [comment]
> Found issue.
> 
> Removing those lines: https://github.com/Wind-Development/WindSpigot/blob/master/WindSpigot-Server/src/main/java/net/minecraft/server/MinecraftServer.java#L667-L677
> 
> Brings 20.00 tps back
> 
> 15:24:19 [INFO]: WindSpigot Performance: 15:24:19 [INFO]: TPS from last 1m, 5m, 15m: 20.0, 20.0, 20.0
> 
> Tested: AMD CPU, JAVA 17, 4GB, no startup flags

After testing this, it seems like the server undersleeps instead of oversleeping.

**Comment by windcolor-dev** [comment]
Can you try out the latest build?

**Comment by Fredh1000** [comment]
There still seems to be the problem. With Java 17 these are the TPS:
![Java17](https://user-images.githubusercontent.com/82319919/169720725-8e663f6f-f9ff-48d1-b199-0bda556662bc.png)

And with Java 11 the TPS are these:
![Java11](https://user-images.githubusercontent.com/82319919/169720756-e560c193-a772-4e23-ba11-dcaf5934f96a.png)

**Comment by Sculas** [comment]
Just curious, is this a problem, and is this a problem WindSpigot should solve, if it's actually an issue in Java?

**Comment by Fejm** [comment]
Wtf. Try /tps command

**Comment by windcolor-dev** [comment]
Can you try out the build from here? https://github.com/Wind-Development/WindSpigot/actions/runs/2375353025

**Comment by FabrisNick** [comment]
![immagine](https://user-images.githubusercontent.com/69034647/169964819-2edeb3b3-a5b0-4ff8-9692-7269afb60f5f.png)
Nice

**Comment by Fredh1000** [comment]
It works!! Finally the TPS are stable and they are as many as they should be even with Java 17 !!! @windcolor-dev

**Comment by Fredh1000** [comment]
![TPSjava17WindSpigot](https://user-images.githubusercontent.com/82319919/169991521-d4096a4d-8db7-4779-bed5-a9b300d1bb78.png)

**Comment by Fejm** [comment]
~~Well, good job with backporting modern tick loop. I have tried to do it myself but without good results. (tps was 19.7...)~~

~~However, i belive that changing this line: 
https://github.com/Wind-Development/WindSpigot/blob/master/WindSpigot-Server/src/main/java/net/minecraft/server/MinecraftServer.java#L669~~

~~to:~~
`
wait -= catchupTime;
`
~~also fixes issue. Correct me if i am wrong.~~

**// Edit**
I was wrong. Modern ticking is solution, stable 20.00 even if flying thru not generated chunks.
