### ISSUE TITLE
Some tips

### ISSUE THREAD

**Issue by Sculas** [Wind-Development/WindSpigot#36]
Hi there, since NachoSpigot is now officially unmaintained I heard about this and I'd like to give some tips.

I really really recommend you to get rid of the "async explosions", it does more bad than good (it literally spawns 500 Java/OS threads, how did I think this would be a good idea?!). The anticrash is also very mediocre and people should use plugins instead, so maybe get rid of that too.

I also recommend you to update the readme, since it looks very outdated (especially the ViaVersion runtime patching, which has been removed long ago and this repo also seems to no longer contain it).

I'm also going to refer to WindSpigot as a fork people can use in the Nacho repository, so you may see some more traffic :)

That's all, good luck! 🙂

**Comment by windcolor-dev** [comment]
Thanks for these tips! Also, thanks to you and all other NachoSpigot contributors for the amazing base to build off of :)

**Comment by Sculas** [comment]
You're welcome, and thank you too for accompanying our journey 🙂

*Oh wow, that's a weird typo. I meant to say "officially unmaintained" heh, not "unofficially unmaintained".*

**Comment by andreasdc** [comment]
![image](https://user-images.githubusercontent.com/82218780/169357611-0754920f-084a-4585-81ea-ef066d3d1002.png)
Hehe just don't follow their path. :) Karma always comes back.

**Comment by Sculas** [comment]
That's a you problem. I hope you don't cause a headache to the developer(s) here at WindSpigot like you did at NachoSpigot and other 1.8 forks 🙂

**Comment by andreasdc** [comment]
> That's a you problem. I hope you don't cause a headache to the developer(s) here at WindSpigot like you did at NachoSpigot and other 1.8 forks 🙂

You are right, for ill people simple interactions can cause headaches, you can try to heal yourself, but that's not the place to spam and discuss about your mental health.

**Comment by Sculas** [comment]
Hmm, good comeback. Still though, didn't ask for a response nor your opinion. You are frustrating developers at Paper, NachoSpigot and hell possibly even others. Maybe you should look at yourself first. Don't continue this and let the maintainer either delete or hide these comments. I'll also block you since I literally cannot stand your childishness. Go touch grass. Thanks.
