### ISSUE TITLE
Could not load config files

### ISSUE THREAD

**Issue by raccoman** [Wind-Development/WindSpigot#41]
**Describe the bug**
"Could not load windspigot.yml, please correct your syntax errors" at server startup

**Bug on latest**
I'm working on the latest WindSpigot version, on a MacBook Pro M1

**To Reproduce**
I cloned the repo, compiled with maven and JDK 11 and simply started the server jar.
(I've also tried to compile with JDK 8)

![image](https://user-images.githubusercontent.com/48388138/169603734-3ec42728-7ccf-4ecf-9261-a6a27e91b56f.png)

**Comment by ghost** [comment]
https://github.com/Wind-Development/WindSpigot/issues/37#issuecomment-1133312933

> I think you’ll need to fix your config since it was messed up by the earlier bug, try going to line 64 in your config and see if there’s any problems around there

**Comment by raccoman** [comment]
Okay, the configuration got messed up. But what configuration should be used? Because the latest release of the spigot from Github uses the 21, while the one used by the compiled spigot is the 25.

**Comment by raccoman** [comment]
I fixed. The problem is that the spigot generates the "async.tnt" config path wrongly

**Comment by windcolor-dev** [comment]
This is a really weird issue... temporary removal of async tnt configuration seems to fix it, but I'm not sure what is wrong with config/comments with this option, all other settings work fine.

**Comment by raccoman** [comment]
Yeah, that's weird

**Comment by windcolor-dev** [comment]
This seems to be fixed on the latest build.
