### ISSUE TITLE
NullPointerException NachoWorldConfig

### ISSUE THREAD

**Issue by totKing** [Wind-Development/WindSpigot#43]
**Describe the bug**
The nacho.yml is not generated. This results in an error.

**Bug on latest**
Yes

**To Reproduce**
Run WindSpigot.jar in an empty folder

**Screenshots**
https://gyazo.com/e4c27ea76d86d2683fc32324d34f91c8
https://gyazo.com/2dd4ff21a033c56a844d12037daac594

**Additional context**
https://paste.twerion.net/hahacuhoni.css

**Additional context**
![unknown](https://user-images.githubusercontent.com/18356351/169628741-da6cbecc-6d75-4830-9276-955dc394654e.png)
<img width="359" alt="2dd4ff21a033c56a844d12037daac594" src="https://user-images.githubusercontent.com/18356351/169628744-c62670bb-6666-4208-84ee-63c629253178.png">

**Comment by windcolor-dev** [comment]
I believe that it is fixed in the latest build.

**Comment by totKing** [comment]
Yes, just tested the latest version. Server starts and nacho.yml is probably no longer in operation, which means that it is not generated.
