### ISSUE TITLE
Incompatibility with Intave AntiCheat

### ISSUE THREAD

**Issue by DrakMC** [Wind-Development/WindSpigot#44]
**Describe the bug**
When running Intave on WindSpigot, there is problem with async feature.

**Bug on latest**
Yes - version 2.1.2

**Expected behavior**
There should be an option to disable certain async features.

**Additional context**
Log: https://pastebin.com/raw/4fM742MG

I've tried to disable all async features in config file, but it doesn't fixed the problem.

**Comment by windcolor-dev** [comment]
Does disabling the async entity tracker still not fix the issue?

**Comment by DrakMC** [comment]
Unfortunately not

**Comment by ghost** [comment]
Looking at the code, it seems that the async entity tracker is always enabled no matter what option you choose on the config

**Comment by DrakMC** [comment]
Thanks for the information. Could you please fix it and release the build?

**Comment by windcolor-dev** [comment]
Async entity tracker config should be fixed on the latest build.

**Comment by windcolor-dev** [comment]
Unfortunately, Intave is a closed source and paid plugin, so I can only guess at fixing compatibility with the async entity tracker enabled.

**Comment by DrakMC** [comment]
It looks like it's fixed. Thanks
