### ISSUE TITLE
Windspigot doesn't support Protocollib 5.0

### ISSUE THREAD

**Issue by Hyronymos1337** [Wind-Development/WindSpigot#46]
**Describe the bug**
We use Protocollib 5.0 to spawn NPCs, with Pandaspigot it works, with WindSpigot it only works with Protocollib 4.0

**Bug on latest**
Bugg exist son latest WindSpigot

**To Reproduce**
we can help debbuging it via WindSpigot Discord or Privat (Hyronymos 🥝#6898)

**Expected behavior**
No Errors

**Comment by windcolor-dev** [comment]
Can you post your NPC spawn code and the errors?

**Comment by Hyronymos1337** [comment]
our npc api: https://paste.twerion.net/uzecudexeb.typescript

example npc that doesnt spawn: https://paste.twerion.net/wutafekavo.typescript

**Comment by windcolor-dev** [comment]
So the NPC that should spawn doesn't appear at all?

**Comment by Hyronymos1337** [comment]
yes

**Comment by windcolor-dev** [comment]
Can you post the part of your NPC code that actually sends the packets?

**Comment by Hyronymos1337** [comment]
should be this: https://paste.twerion.net/uzabegeloy.typescript

**Comment by windcolor-dev** [comment]
Can you show the "sendPacket" method in your "Reflections" class?

**Comment by totKing** [comment]
https://paste.twerion.net/dexogilaqu.typescript

**Comment by windcolor-dev** [comment]
> https://paste.twerion.net/dexogilaqu.typescript

Isn't that code for 1.18? Also, doesn't that code just use NMS instead of ProtocolLib to send packets?

**Comment by Sculas** [comment]
^ Not only that, why are you using both ProtocolLib and NMS? Using both makes no sense, it's like having 2 dependencies that do the same.

**Comment by totKing** [comment]
> > https://paste.twerion.net/dexogilaqu.typescript
> 
> Isn't that code for 1.18? Also, doesn't that code just use NMS instead of ProtocolLib to send packets?

Sry, wrong class pulled from the 1.18 version xd

https://paste.twerion.net/ekofexizen.typescriptd

**Comment by windcolor-dev** [comment]
So what's incompatible? Does sending packets via NMS not work while using ProtocolLib 5.0?

**Comment by Hyronymos1337** [comment]
> So what's incompatible? Does sending packets via NMS not work while using ProtocolLib 5.0?

probaly both


> ^ Not only that, why are you using both ProtocolLib and NMS? Using both makes no sense, it's like having 2 dependencies that do the same.

doenst matter, we dont have the issue on native paper 1.8.8, flamepaper, pandaspigot or on 1.18.2 forks

**Comment by windcolor-dev** [comment]
Can you elaborate on your problem? I don't understand what the issue is.
