### ISSUE TITLE
Throwed projectile is not visible

### ISSUE THREAD

**Issue by DrakMC** [Wind-Development/WindSpigot#48]
**Describe the bug**
When I throw a projectile like a snowball or an arrow shot with a bow, I can't see it at all.

**Bug on latest**
Yes - 2.1.3

**To Reproduce**
1. Throw projectile - for example snowball or shoot an arrow with a bow
2. You can't see throwed projectile

**Expected behavior**
Throwed projectile should be visible.

**Comment by DrakMC** [comment]
Fixed in the latest version

**Comment by windcolor-dev** [comment]
Is #51 fixed also?

**Comment by DrakMC** [comment]
I will test it.

**Comment by DrakMC** [comment]
Probably it's fixed
