### ISSUE TITLE
Some players are invisible sometimes

### ISSUE THREAD

**Issue by DrakMC** [Wind-Development/WindSpigot#51]
**Describe the bug**
Some players are sometimes invisible. The problem is only with this fork. NachoSpigot has no problem.

**Bug on latest**
Yes

**To Reproduce**
I don't know when it happens exactly, but it's common.

**Comment by ghost** [comment]
Try with async entity tracker disabled in windspigot.yml and let us know if it still occurs

**Comment by windcolor-dev** [comment]
After looking through the code, it might in fact be due to async entity tracking being disabled.

**Comment by DrakMC** [comment]
I've had async entity tracker disabled

**Comment by ghost** [comment]
Are you using 2.1.2 or latest dev build?

**Comment by DrakMC** [comment]
Latest - 2.1.3

**Comment by windcolor-dev** [comment]
Can you try this? https://github.com/Wind-Development/WindSpigot/actions/runs/2374546299

**Comment by windcolor-dev** [comment]
Please note that this is based on v2.1.2, so you may have to regenerate your windspigot.yml

**Comment by windcolor-dev** [comment]
LMK if this fixes #48 also

**Comment by DrakMC** [comment]
I changed server.jar back to NachoSpigot because of these bugs. However, I'll try it and let you know.

**Comment by DrakMC** [comment]
Async entity tracker is enabled while it's disabled in the configuration file.

**Comment by windcolor-dev** [comment]
Oh, I forgot to add that fix, try re-downloading the latest release.

**Comment by DrakMC** [comment]
Knockback is still broken. I haven't tested the invisible player bug because this fork is not stable for production.

**Comment by ghost** [comment]
> Knockback is still broken. I haven't tested the invisible player bug because this fork is not stable for production.

The invisible player and projectile bug will probably be fixed by #55 since they are both seemingly caused by the multithreaded entity tracker

**Comment by windcolor-dev** [comment]
https://github.com/Wind-Development/WindSpigot/issues/48#issuecomment-1139950317
