### ISSUE TITLE
Weird knockback

### ISSUE THREAD

**Issue by DrakMC** [Wind-Development/WindSpigot#52]
**Describe the bug**
Knockback is different from NachoSpigot. Players are complaining about him. NachoSpigot had no problem.

**Bug on latest**
Yes

**Comment by ghost** [comment]
~~Should be fixed when the 2.1.2 hotfix is released~~

**Comment by windcolor-dev** [comment]
The knockback is indeed different from NachoSpigot, switch to the kohi profile instead of vanilla to use NachoSpigot's default knockback.

**Comment by ghost** [comment]
Reopen, this is not fixed. @windcolor-dev

**Comment by windcolor-dev** [comment]
What's broken?

**Comment by ghost** [comment]
The vanilla profile isn't vanilla knockback

**Comment by fixca** [comment]
I think you should make the "true" vanilla Knockback (I think it's what he wants).
I mean, the KB is not "true" vanilla Knockback currently since the mot values are different.

**Comment by ghost** [comment]
The “vanilla” and “kohi” values aren’t even close to the true values

**Comment by windcolor-dev** [comment]
Oh, do you know the correct values?

**Comment by ghost** [comment]
I’m working on a PR for it atm

**Comment by windcolor-dev** [comment]
Nice
