### ISSUE TITLE
Ghost blocks

### ISSUE THREAD

**Issue by andreasdc** [Wind-Development/WindSpigot#59]
When you set player's view distance with api to lower than what client have, you see ghost blocks/chunks, especially when walking away from them.

**Comment by windcolor-dev** [comment]
Does this happen on NachoSpigot/Paper?

**Comment by andreasdc** [comment]
> Does this happen on NachoSpigot/Paper?

I don't have this information, I know that it happens on vanilla 1.8.

**Comment by windcolor-dev** [comment]
Vanilla Minecraft does not even support plugins, so you can't use the view distance API for players on it...

**Comment by andreasdc** [comment]
> Vanilla Minecraft does not even support plugins, so you can't use the view distance API for players on it...

What do you mean?

**Comment by windcolor-dev** [comment]
This bug can't exist on vanilla Minecraft, so what do you mean by

> I don't have this information, I know that it happens on vanilla 1.8.

**Comment by andreasdc** [comment]
> This bug can't exist on vanilla Minecraft, so what do you mean by
> 
> > I don't have this information, I know that it happens on vanilla 1.8.

Vanilla 1.8 client.

**Comment by windcolor-dev** [comment]
Oh, ok. Can you test if this happens when you use PaperSpigot as the server JAR?

**Comment by andreasdc** [comment]
> Oh, ok. Can you test if this happens when you use PaperSpigot as the server JAR?

I can't because it doesn't support my Java version.

**Comment by andreasdc** [comment]
I did some investigating and this bug is related to block changes outside of player's view distance. What can we do about it?

**Comment by windcolor-dev** [comment]
I don't think we can do anything about it if it's a client side issue.

**Comment by andreasdc** [comment]
> I don't think we can do anything about it if it's a client side issue.

The only idea that comes to me is checking for chunk unloads/distance, what do you think?

**Comment by andreasdc** [comment]
Why closed?

**Comment by ghost** [comment]
It's something we cannot fix as it's a client side issue.

**Comment by andreasdc** [comment]
I think it's fixable without any problem. Did you make any tests or how do you know that?

**Comment by ghost** [comment]
The client keeps their render distance higher than the server's view distance so the server will only send block changes within that view distance. There's nothing we can do other than remove the API, which we can't due to compatibility with plugins.

**Comment by andreasdc** [comment]
> The client keeps their render distance higher than the server's view distance so the server will only send block changes within that view distance. There's nothing we can do other than remove the API, which we can't due to compatibility with plugins.

The issue is about player's view distance.

**Comment by ghost** [comment]
Render distance is what's rendered by the client. View distance is the range of blocks in which the server sends block changes in to the client, and these are meant to be the same, but updating view distance on the server doesn't update the render distance, only visa-versa, so only the blocks outside of the view distance but still in the render distance will stay and not change from any block change packets or be "ghost blocks".

**Comment by andreasdc** [comment]
So the fix could be stopping block updates when they are further than client's view distance, right?

**Comment by ghost** [comment]
That's what's already happening, which is what causes the ghost blocks

**Comment by andreasdc** [comment]
I didn't find anything like that in the code, can you show me?

**Comment by ghost** [comment]
I don't know where exactly, however the server only sends block change packets to players who's view distance in has the block being changed. This is to not require sending block change packets to blocks that the player cannot see.

**Comment by andreasdc** [comment]
I think you made a mistake with sending block packets caused by normal server actions, not custom packets.
