### ISSUE TITLE
Poor MobAI command

### ISSUE THREAD

**Issue by ghost** [Wind-Development/WindSpigot#78]
**Describe the bug**
The way /mobai works is extremely poor. It toggles each world's mob AI, so one world which had it off and another which haves it on, would respectively have on and off, and the message sent to the player would say that mob AI on all worlds was turned on/off, even though it is actually only the status for the last world checked.

**Expected behavior**
You'd expect mob AI to be enabled/disabled for all worlds, or instead having an option to choose the world to toggle mob AI.

**Bug on latest**
Yes, since 1.3

**Additional context**
The related file is https://github.com/Wind-Development/WindSpigot/blob/master/WindSpigot-Server/src/main/java/ga/windpvp/windspigot/commands/MobAICommand.java.

**Comment by windcolor-dev** [comment]
The command now handles mob AI toggling globally, I didn't consider per world settings when I added this.
