### ISSUE TITLE
BUILD FAILURE

### ISSUE THREAD

**Issue by r9x** [Wind-Development/WindSpigot#86]
![image](https://user-images.githubusercontent.com/103152375/175792233-b92bc133-01a2-48fc-aa3d-39fdd1a808be.png)

![image](https://user-images.githubusercontent.com/103152375/175792271-33ea39ef-9bfa-4e11-89f3-d0cf060dfbba.png)

**Comment by ghost** [comment]
Neither of your screenshots are helpful at all. The first image only shows that the build failed and the second is a bug with IntelliJ and it builds fine on CI and on my computer. Try clearing your maven cache, as this seemingly isn't a WindSpigot issue.

**Comment by r9x** [comment]
> Neither of your screenshots are helpful at all. The first image only shows that the build failed and the second is a bug with IntelliJ and it builds fine on CI and on my computer. Try clearing your maven cache, as this seemingly isn't a WindSpigot issue.

Can you send a pom file related to the Wind Spigot-Server module
