### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by omgloer** [Wind-Development/WindSpigot#87]
Hello my server crashed with a long error message here it is 
 Post too long to put here
https://pastebin.com/qR4iU1Vy

**Comment by ghost** [comment]
Looks like an issue with one of your plugins

**Comment by omgloer** [comment]
It worked perfectly for 2 years with spigot and paper 1.8 you think nacho is not compatible with all?

**Comment by ghost** [comment]
I’ll look into it

**Comment by Ethylaaaa** [comment]
I have the same problem but with paper spigot 1.8 there is no crash.

**Comment by omgloer** [comment]
I've never had this problem again even though I haven't deleted anything since.

**Comment by omgloer** [comment]
I believe it was the 'no respawn screen' plugin as I only removed it

**Comment by Ethylaaaa** [comment]
I will test this but I don't seem to use this :c
