### ISSUE TITLE
hoe no enchantment 

### ISSUE THREAD

**Issue by omgloer** [Wind-Development/WindSpigot#93]
Hello, when you place a hoe in the enchantment table there is no enchantment offered?
![Capture](https://user-images.githubusercontent.com/93183628/177826976-1af1aefd-5ce2-48dc-8c2f-6edf0030fbd9.PNG)

**Comment by windcolor-dev** [comment]
Isn't this normal behavior?

**Comment by rektbydead** [comment]
yes it is ...
