### ISSUE TITLE
Plugin Compatability

### ISSUE THREAD

**Issue by FirephoenixX02** [Wind-Development/WindSpigot#98]
Hi
I would like to switch my Backend Servers from my Server Network, from normal Spigot to WindSpigot to improve Performance.
But I only want to switch if all normal Spigot Plugins also work with WindSpigot.
I hope someone can answer my question.

**Comment by Fredh1000** [comment]
WindSpigot is a fork of NachoSpigot which is a fork of TacoSpigot which is a fork of Paper which is itself a fork of Spigot 1.8.8. I think I've told you everything. The bukkit api has it all craftbukkit forks.

**Comment by windcolor-dev** [comment]
It should be fine for the most part, but I would test before putting it in production.
